name: one_for_all_generator
description: Code generator to make communication between Flutter and the host platform easier and more secure
version: 2.0.2
repository: https://github.com/BreX900/mek-packages/tree/main/one_for_all_generator
homepage: https://pub.dev/packages/one_for_all
topics:
  - platforms-communication
  - build-runner
  - codegen
  - mek-packages

environment:
  sdk: ^3.0.0

scripts:
  publish: dart pub publish

dependencies:
  args: ^2.4.2

  logging: ^1.1.0
  recase: ^4.1.0
  collection: ^1.18.0
  pure_extensions: ^5.0.0
  equatable: ^2.0.5

  path: ^1.8.3
  glob: ^2.1.2

  analyzer: '>=7.4.0 <9.0.0'
  source_gen: '>=3.1.0 <5.0.0'
  code_builder: ^4.4.0
  dart_style: ^3.0.0

  one_for_all: ^1.1.0

dev_dependencies:
  mek_lints: ^5.0.0

dependency_overrides:
  one_for_all:
    path: ../one_for_all
